#![allow(unused_variables)]

//! Tauri IPC commands for `Session` lifecycle and membership (Module 1).
//!
//! These handlers are thin per the repository's command convention: they
//! parse/validate arguments and delegate to `services/` (not yet
//! implemented) for the actual logic. `Err(String)` payloads cross the IPC
//! boundary as plain messages; each command's `# Errors` section below
//! describes what conditions they are expected to cover once implemented.

use uuid::Uuid;

use crate::models::{Session, SessionStatus};

/// Creates a new session under `project_id`.
///
/// # Arguments
///
/// * `name` — optional session name; when `None`, a default name is expected
///   to be generated by the service layer.
///
/// # Errors
///
/// Expected to fail if `project_id` does not reference an existing project.
#[tauri::command]
pub fn create_session(project_id: Uuid, name: Option<String>) -> Result<Session, String> {
    Err("create_session: not implemented".to_string())
}

/// Fetches a single session by id.
///
/// # Errors
///
/// Expected to fail if no session with `session_id` exists.
#[tauri::command]
pub fn get_session(session_id: Uuid) -> Result<Session, String> {
    Err("get_session: not implemented".to_string())
}

/// Lists all sessions belonging to `project_id`.
///
/// # Errors
///
/// Expected to fail if `project_id` does not reference an existing project.
#[tauri::command]
pub fn get_sessions_by_project(project_id: Uuid) -> Result<Vec<Session>, String> {
    Err("get_sessions_by_project: not implemented".to_string())
}

/// Renames an existing session.
///
/// # Errors
///
/// Expected to fail if no session with `session_id` exists.
#[tauri::command]
pub fn update_session_name(session_id: Uuid, new_name: String) -> Result<Session, String> {
    Err("update_session_name: not implemented".to_string())
}

/// Updates a session's [`SessionStatus`] (e.g. `Active` → `Archived`).
///
/// # Errors
///
/// Expected to fail if no session with `session_id` exists.
#[tauri::command]
pub fn update_session_status(session_id: Uuid, status: SessionStatus) -> Result<Session, String> {
    Err("update_session_status: not implemented".to_string())
}

/// Assigns an already-imported image to a session.
///
/// Does not itself recompute [`Session::date_start`]/[`Session::date_end`];
/// call [`recalculate_session_date_range`] afterwards if the caller needs
/// the session's date range kept in sync.
///
/// # Errors
///
/// Expected to fail if `session_id` or `image_id` does not reference an
/// existing record.
#[tauri::command]
pub fn assign_image_to_session(session_id: Uuid, image_id: Uuid) -> Result<(), String> {
    Err("assign_image_to_session: not implemented".to_string())
}

/// Recomputes [`Session::date_start`]/[`Session::date_end`] as the
/// min/max `captured_at` across the session's assigned images.
///
/// # Errors
///
/// Expected to fail if no session with `session_id` exists.
#[tauri::command]
pub fn recalculate_session_date_range(session_id: Uuid) -> Result<(), String> {
    Err("recalculate_session_date_range: not implemented".to_string())
}

/// Deletes a session.
///
/// # Errors
///
/// Expected to fail if no session with `session_id` exists.
#[tauri::command]
pub fn delete_session(session_id: Uuid) -> Result<(), String> {
    Err("delete_session: not implemented".to_string())
}
