//! Data model definitions for `Session`, `Project`, and `Image`.
//!
//! These are the canonical persisted records for Module 1's organisational
//! hierarchy:
//!
//! ```text
//! Project
//! └── Session (date_start/date_end derived from its images)
//!     └── Image (one persisted record per imported file)
//! ```
//!
//! [`Image`] here is the storage-side record (id, path, location, capture
//! time, plus the most-queried EXIF-derived fields). It carries the
//! acceptance-critical metadata (GPS, date, altitude, resolution) as
//! nullable columns so images with missing tags still persist — see
//! [`crate::modules::module_01::REQUIRED_METADATA_FIELDS`]. For the full
//! EXIF/XMP telemetry captured during import (camera settings, flight
//! data, etc.), see [`crate::models::image::ImageMetadata`], and
//! [`crate::models::image`] generally for the in-flight import pipeline
//! types that precede a record landing here.
//!
//! # A Note on Temporal Representation
//!
//! These structs use two different datetime types on purpose — don't mix
//! them up:
//! - `NaiveDateTime` (no timezone attached) is used for fields sourced from
//!   the drone camera's EXIF metadata (`date_start`, `date_end`,
//!   `captured_at`). Most cameras write EXIF timestamps as local time at the
//!   capture location, with no UTC offset recorded, so `NaiveDateTime` is
//!   the honest representation here. Don't assume these values are UTC, and
//!   don't compare them directly against the `DateTime<Utc>` fields below
//!   without an explicit timezone conversion.
//! - `DateTime<Utc>` (always UTC) is used for fields the system generates
//!   itself when a record is created or modified (`created_at`,
//!   `updated_at`) — these have nothing to do with EXIF data.

use chrono::{DateTime, NaiveDateTime, Utc};
use serde::{Deserialize, Serialize};
use uuid::Uuid;

#[derive(Debug, Clone, Serialize, Deserialize)]
#[serde(rename_all = "camelCase")]
pub struct Project {
    pub id: Uuid,
    pub name: String,
}

#[derive(Debug, Clone, Copy, Serialize, Deserialize, PartialEq, Eq)]
#[serde(rename_all = "lowercase")]
pub enum SessionStatus {
    Active,
    Archived,
}

impl SessionStatus {
    /// Text stored in the `session.status` column.
    pub fn as_str(self) -> &'static str {
        match self {
            SessionStatus::Active => "active",
            SessionStatus::Archived => "archived",
        }
    }

    /// Inverse of [`as_str`](Self::as_str); unknown values read as `Active`.
    pub fn from_db(raw: &str) -> Self {
        match raw {
            "archived" => SessionStatus::Archived,
            _ => SessionStatus::Active,
        }
    }
}

#[derive(Debug, Clone, Serialize, Deserialize)]
#[serde(rename_all = "camelCase")]
pub struct Session {
    pub id: Uuid,
    pub project_id: Uuid,
    pub name: String,
    /// Timezone-naive. Computed as the minimum `captured_at` value across all
    /// images associated with this session. Represents local camera time; this
    /// value does NOT represent Coordinated Universal Time (UTC).
    pub date_start: NaiveDateTime,
    /// Timezone-naive. Computed as the maximum `captured_at` value across all
    /// images associated with this session. Represents local camera time; this
    /// value does NOT represent Coordinated Universal Time (UTC).
    pub date_end: NaiveDateTime,
    pub status: SessionStatus,
    /// Timezone-aware; invariably expressed in UTC. Generated by the system at
    /// the time of record creation.
    pub created_at: DateTime<Utc>,
    /// Timezone-aware; invariably expressed in UTC. Generated by the system at
    /// the time of record modification.
    pub updated_at: DateTime<Utc>,
}

/// A persisted image record belonging to a session.
///
/// This is the canonical stored record. Location, capture time, and the
/// most-queried EXIF fields are nullable: an image with missing metadata is
/// still imported, with absent tags stored as `NULL` (M1-23 "incomplete
/// metadata"). Use [`crate::modules::module_01::missing_required_fields`]
/// to recover which required fields are missing for a stored record.
#[derive(Debug, Clone, PartialEq, Serialize, Deserialize)]
#[serde(rename_all = "camelCase")]
pub struct Image {
    pub id: Uuid,
    pub session_id: Uuid,
    /// Absolute path to the original file (not a directory path, and not a
    /// reference to any derived or multi-variant representation thereof).
    pub file_path: String,
    /// GPS latitude in decimal degrees. `None` when the source image has no
    /// GPS tags.
    pub location_lat: Option<f64>,
    /// GPS longitude in decimal degrees. `None` when the source image has no
    /// GPS tags.
    pub location_lon: Option<f64>,
    /// Timezone-naive. Derived from EXIF metadata, representing local camera
    /// time at the moment of image acquisition (the majority of camera systems
    /// do not encode a timezone offset within their EXIF data). Serves as the
    /// primary source for the computation of the `date_start` and `date_end`
    /// fields of the associated `Session`. `None` when the source image has
    /// no `DateTimeOriginal` tag; such images are skipped by the session
    /// date-range derivation.
    pub captured_at: Option<NaiveDateTime>,
    /// GPS altitude in metres above sea level (EXIF). `None` when absent.
    pub gps_altitude_m: Option<f64>,
    /// Image width in pixels. `None` when dimensions could not be read.
    pub width: Option<u32>,
    /// Image height in pixels. `None` when dimensions could not be read.
    pub height: Option<u32>,
    /// Detected image format, as a lowercase string (`"jpeg"` / `"dng"`).
    pub format: Option<String>,
    /// Camera manufacturer (e.g. `"DJI"`). `None` when absent.
    pub make: Option<String>,
    /// Camera model name (e.g. `"Mavic 3"`). `None` when absent.
    pub camera_model: Option<String>,
}
