//! Data model definitions for `Session`, `Project`, and `Image`.
//!
//! # A Note on Temporal Representation
//! The structures defined herein deliberately employ two distinct categories of
//! datetime types; these categories must not be conflated:
//! - `NaiveDateTime` (timezone-naive; i.e., devoid of associated timezone
//!   information) is employed for fields whose values are derived from the EXIF
//!   metadata embedded by the drone's onboard camera (namely, `date_start`,
//!   `date_end`, and `captured_at`). The majority of camera systems record EXIF
//!   timestamps as local time relative to the location at which the photograph
//!   was captured, without encoding a corresponding UTC offset. Accordingly,
//!   `NaiveDateTime`—rather than `DateTime<Utc>`—constitutes the appropriate
//!   representation in this context. These values MUST NOT be assumed to
//!   represent Coordinated Universal Time (UTC), nor should they be directly
//!   compared against the `DateTime<Utc>` fields described below without
//!   explicit and deliberate timezone conversion.
//! - `DateTime<Utc>` (timezone-aware, invariably expressed in Coordinated
//!   Universal Time) is employed for fields that are generated programmatically
//!   by the system at the moment a given record is created or subsequently
//!   modified (namely, `created_at` and `updated_at`), as opposed to values
//!   derived from EXIF metadata.

use chrono::{DateTime, NaiveDateTime, Utc};
use serde::{Deserialize, Serialize};
use uuid::Uuid;

#[derive(Debug, Clone, Serialize, Deserialize)]
#[serde(rename_all = "camelCase")]
pub struct Project {
    pub id: Uuid,
    pub name: String,
}

#[derive(Debug, Clone, Copy, Serialize, Deserialize, PartialEq, Eq)]
#[serde(rename_all = "lowercase")]
pub enum SessionStatus {
    Active,
    Archived,
}

#[derive(Debug, Clone, Serialize, Deserialize)]
#[serde(rename_all = "camelCase")]
pub struct Session {
    pub id: Uuid,
    pub project_id: Uuid,
    pub name: String,
    /// Timezone-naive. Computed as the minimum `captured_at` value across all
    /// images associated with this session. Represents local camera time; this
    /// value does NOT represent Coordinated Universal Time (UTC).
    pub date_start: NaiveDateTime,
    /// Timezone-naive. Computed as the maximum `captured_at` value across all
    /// images associated with this session. Represents local camera time; this
    /// value does NOT represent Coordinated Universal Time (UTC).
    pub date_end: NaiveDateTime,
    pub status: SessionStatus,
    /// Timezone-aware; invariably expressed in UTC. Generated by the system at
    /// the time of record creation.
    pub created_at: DateTime<Utc>,
    /// Timezone-aware; invariably expressed in UTC. Generated by the system at
    /// the time of record modification.
    pub updated_at: DateTime<Utc>,
}

#[derive(Debug, Clone, Serialize, Deserialize)]
#[serde(rename_all = "camelCase")]
pub struct Image {
    pub id: Uuid,
    pub session_id: Uuid,
    /// Absolute path to the original file (not a directory path, and not a
    /// reference to any derived or multi-variant representation thereof).
    pub file_path: String,
    pub location_lat: f64,
    pub location_lon: f64,
    /// Timezone-naive. Derived from EXIF metadata, representing local camera
    /// time at the moment of image acquisition (the majority of camera systems
    /// do not encode a timezone offset within their EXIF data). Serves as the
    /// primary source for the computation of the `date_start` and `date_end`
    /// fields of the associated `Session`.
    pub captured_at: NaiveDateTime,
}
