//! Data model definitions for `Session`, `Project`, and `Image`.
//!
//! # A Note on Temporal Representation
//!
//! These structs use two different datetime types on purpose — don't mix
//! them up:
//! - `NaiveDateTime` (no timezone attached) is used for fields sourced from
//!   the drone camera's EXIF metadata (`date_start`, `date_end`,
//!   `captured_at`). Most cameras write EXIF timestamps as local time at the
//!   capture location, with no UTC offset recorded, so `NaiveDateTime` is
//!   the honest representation here. Don't assume these values are UTC, and
//!   don't compare them directly against the `DateTime<Utc>` fields below
//!   without an explicit timezone conversion.
//! - `DateTime<Utc>` (always UTC) is used for fields the system generates
//!   itself when a record is created or modified (`created_at`,
//!   `updated_at`) — these have nothing to do with EXIF data.

use chrono::{DateTime, NaiveDateTime, Utc};
use serde::{Deserialize, Serialize};
use uuid::Uuid;

#[derive(Debug, Clone, Serialize, Deserialize)]
#[serde(rename_all = "camelCase")]
pub struct Project {
    pub id: Uuid,
    pub name: String,
}

#[derive(Debug, Clone, Copy, Serialize, Deserialize, PartialEq, Eq)]
#[serde(rename_all = "lowercase")]
pub enum SessionStatus {
    Active,
    Archived,
}

#[derive(Debug, Clone, Serialize, Deserialize)]
#[serde(rename_all = "camelCase")]
pub struct Session {
    pub id: Uuid,
    pub project_id: Uuid,
    pub name: String,
    /// Timezone-naive. Computed as the minimum `captured_at` value across all
    /// images associated with this session. Represents local camera time; this
    /// value does NOT represent Coordinated Universal Time (UTC).
    pub date_start: NaiveDateTime,
    /// Timezone-naive. Computed as the maximum `captured_at` value across all
    /// images associated with this session. Represents local camera time; this
    /// value does NOT represent Coordinated Universal Time (UTC).
    pub date_end: NaiveDateTime,
    pub status: SessionStatus,
    /// Timezone-aware; invariably expressed in UTC. Generated by the system at
    /// the time of record creation.
    pub created_at: DateTime<Utc>,
    /// Timezone-aware; invariably expressed in UTC. Generated by the system at
    /// the time of record modification.
    pub updated_at: DateTime<Utc>,
}

/// A persisted image record belonging to a session.
///
/// This is the canonical stored record. For the richer EXIF/XMP-derived
/// metadata captured during import (dimensions, camera settings, flight
/// telemetry, etc.), see [`crate::models::image::ImageMetadata`].
#[derive(Debug, Clone, Serialize, Deserialize)]
#[serde(rename_all = "camelCase")]
pub struct Image {
    pub id: Uuid,
    pub session_id: Uuid,
    /// Absolute path to the original file (not a directory path, and not a
    /// reference to any derived or multi-variant representation thereof).
    pub file_path: String,
    pub location_lat: f64,
    pub location_lon: f64,
    /// Timezone-naive. Derived from EXIF metadata, representing local camera
    /// time at the moment of image acquisition (the majority of camera systems
    /// do not encode a timezone offset within their EXIF data). Serves as the
    /// primary source for the computation of the `date_start` and `date_end`
    /// fields of the associated `Session`.
    pub captured_at: NaiveDateTime,
}
